apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobin-deployment
  namespace: nginx-ingress
  labels:
    app: webapp1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webapp1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: mobinwebapp1
        image: smobinulla/nginxmob:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp1svc
  namespace: nginx-ingress
  labels:
    app: webapp1
spec:
  selector:
    app: webapp1
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
