apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resources-1
  namespace: nginx-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: webapp1.mubeentech.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: webapp1svc
            port:
              number: 80
  - host: webapp2.mubeentech.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: webapp2svc
            port:
              number: 80

